### ISSUE TITLE
Include `data` directory OR script to produce it

### ISSUE THREAD

**Issue by mathiasbynens** [cameronhunter/unicode-tr51-emoji#2]
It would be useful to either include the `data` directory in the repository, or to add scripts to produce it before building:

```
mkdir -p data/v{1,2}.0;
curl -o data/v1.0/emoji-data.txt http://unicode.org/Public/emoji/1.0/emoji-data.txt;
curl -o data/v2.0/emoji-data.txt http://unicode.org/Public/emoji/2.0/emoji-data.txt;
```

Maybe the above could be `npm run download` which is executed as part of `npm run build`?

**Comment by cameronhunter** [comment]
Hmm, I didn't mean to ignore it – I'll add it to the repo. I like the idea of downloading them, though unsure what the advantage is over just including them?

**Comment by mathiasbynens** [comment]
I’d prefer including them in the repository, too. I just assumed you didn’t want that (since you hadn’t done so). :)

**Comment by cameronhunter** [comment]
Added!
